@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Jun 16 14:29:34 +0500 2026
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim pipeline_tb_behav -key {Behavioral:sim_1:Functional:pipeline_tb} -tclbatch pipeline_tb.tcl -view C:/Users/UnitechSolutions/Documents/Vivado xlinx/bsce24054_lab_8_10_11_12/bsce24054_lab8_10_11_12/pipeline_tb_behav.wcfg -log simulate.log"
call xsim  pipeline_tb_behav -key {Behavioral:sim_1:Functional:pipeline_tb} -tclbatch pipeline_tb.tcl -view C:/Users/UnitechSolutions/Documents/Vivado xlinx/bsce24054_lab_8_10_11_12/bsce24054_lab8_10_11_12/pipeline_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
